from vo.customer_err import CustomError

Err_System = CustomError(10000, "系统异常")